### ISSUE TITLE
Change of lanes

### ISSUE THREAD

**Issue by Kuppharish** [JunshengFu/autonomous-driving-lane-departure-warning#1]
@JunshengFu This code will not work when there is a change of lanes because during the perspective transform you are giving the lane boundaries as input(src,dst) but when there is a change in lanes it still uses the old values which will give huge errors. Is there any solution for this?
Thankyou

**Comment by JunshengFu** [comment]
The perspective transform is used to warp the image from front view to bird view. And it can be fixed once your camera is fixed. So, we only need to select one frame (any suitable frame) to find the (src, dst).

In order to choose the right perspective transform, I did in [this way](https://github.com/JunshengFu/driving-lane-departure-warning#3-use-perspective-transform-to-see-the-image-in-bird-view).  In order to get the correct perspective transform for you camera setting, you need to calibrate your camera.

For "lane changing video", there is one demo in the second last section.
